<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
                           http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.0.xsd
                           http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd">




<aop:aspectj-autoproxy/>

<bean name="triangle" class="org.crescent.model.Triangle">
<property name="name" value="Triangle name"/>
</bean>


<bean name="circle" class="org.crescent.model.Circle">
<!-- <property name="name" value="Circle name"/>  comment it as we are purposely  throwing exception -->
</bean>


<bean name="shapeService" class="org.crescent.service.ShapeService"  autowire="byName" />

<bean name="loggingAspect" class="org.crescent.aspect.LoggingAspect"/>
</beans>